### ISSUE TITLE
Extend documentation regarding octal mode

### ISSUE THREAD

**Issue by dduranr** [tattersoftware/codeigniter4-permits#15]
I managed to install your library and also successfully used the mayCreate, mayUpdate methods, etc. Everything seems to work perfect!

I only need one thing to finish integrating your library into my project: knowing exactly how the octal mode works to assign permissions.

Unfortunately the documentation you provide on your Github is short and not very detailed, so I have not been able to understand how exactly to assign permissions using the **chmod-style four-digit octal mode**. 

I have managed to identify the octal mode for several combinations of permissions, although obviously I'm missing many. I admit that I have managed to identify these octal combinations without knowing what I am doing. I've done it blindly, simply swapping one number for another.

Could you please extend your documentation on this, explaining in more detail how to assign one permission or another, or various combinations of them?

I think your library is great and powerful, my God, and I think it absolutely deserves that we talk about its documentation and extend it for the good of all.

Thank you very much!

**Comment by MGatner** [comment]
Sure thing. This library could definitely use better docs in general. If you are not familiar with octal modes in general you can read on that elsewhere, but briefly you "add up" these possible values to get what you want:
* 4 = read
* 2 = write
* 1 = execute (not used here)

And then values are supplied in order: owner, group, world. So `0640` means "owner can read and write, group can read, and world has no permission." We also use the "domain" convention here, you can think of it like the "parent" or "folder" - so in the first example the permissions apply to existing objects, but by adding the domain we control who can create and list items.

You can check the code in the model trait (https://github.com/tattersoftware/codeigniter4-permits/blob/develop/src/Traits/PermitsTrait.php) for the definitive behavior, but here's the gist of the "bits" in order highest to lowest (we'll use the default as an example: `04664`.

* **Domain** (initial `04`): controls access to list items and create new items; default is list only
* **Owner** (first `6`): user access to items they created; default they can read and write
* **Group** (next `6`): access for users in the same group as the user who made the item; default is read and write
* **World** (final `4`): access for anyone else, including unauthenticated users; default is read only

I hope that helps!

**Comment by MGatner** [comment]
New docs cover all these settings, which are drastically different in version 3.
